### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by psvenk** [katiejolly/30-day-maps-2020#2]
These are all great maps; thank you for sharing them. I'm thinking of using your code for the Virginia urban/suburban/rural map (`20-population`) to make a more generalized map for other states, but first I wanted to check if you meant to add an open-source license to this repository (such as the [MIT License](https://choosealicense.com/licenses/mit/) or the [GNU GPL](https://choosealicense.com/licenses/gpl-3.0/)). More information about the issues with a repository unlicensed can be found [here](https://choosealicense.com/no-permission/). Thanks!

**Comment by katiejolly** [comment]
Thank you for reaching out! I will add a license tomorrow, I just need to look through the options first.
My two requests for using this code are that it 
a) not be used for commercial purposes and
b) attribution is given to me for the original code
I think the MIT license will be fine, although it doesn't cover the commercial use to my knowledge. I request that because this code is something that's meant to be a learning resource, although I won't put a strict license on it.

**Comment by katiejolly** [comment]
And out of curiosity, what are you planning to use the maps for?

**Comment by psvenk** [comment]
Thank you for your speedy response! I found your blog post by a Web search because I wanted a map not of population density _per se_ but rather of urban, suburban, and rural parts of each state. Believe it or not, this was just to satiate my own curiosity, and I wasn't planning on doing anything much; I thought that I would share the more general code in case anyone finds it useful (upon getting your permission, of course).

As for licensing, I understand your concern regarding commercial usage but I would like to add a word of caution about including an outright prohibition: such a condition violates the definitions of open source and free software and can cause license compatibility issues (because most common licenses contain no such clause and therefore non-commercial projects using them won't be able to use your code). If your concern is mainly that someone may profit from your work without giving anything in return, you may be interested in a copyleft license like the GNU GPL or the Mozilla Public License, which mandate that all derivative works release their source code (the GPL mandates that the entire source code be released while the MPL just requires the parts based on your code to be released). More info: https://opensource.stackexchange.com/questions/9747/which-fsf-or-osi-approved-licenses-limit-corporate-usage-in-spirit-but-not-in

Sorry for my somewhat long response, and thanks again for the maps and code!

**Comment by psvenk** [comment]
Fixed in 0082c2bd04. Thanks @katiejolly!

**Comment by psvenk** [comment]
By the way, my modifications to the code are at <https://github.com/psvenk/30-day-maps-2020> (`main` branch), in case you're interested. I'll rebase that on upstream to include the text of the GPL.
